- ANBDConsumer/ANBDConsumer/Common/Util/UserStore.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Article/View/ArticleDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Article/ViewModel/ArticleViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Authentication/ViewModel/AuthenticationViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Chat/ViewModel/ChatViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Home/ViewModel/HomeViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Report/ViewModel/ReportViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/ViewModel/TradeViewModel.swift
> design: Alert 및 Error 문구 수정

- ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/ArticleListView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeCreateView.swift
<br>
<br>
<br>
- 변경사항을 체크하는 onChange가 너무 복잡한 것 같아용.... 
- 혹시 좋은 방법있으면 알려주시면 감사하겠습니다...-.- _._
<br><br>
> refactor: trade qa

- ANBDConsumer/ANBDConsumer/Presentaion/Report/View/ReportView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Report/ViewModel/ReportViewModel.swift
> refactor: 신고하기 placeholder 수정

- ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/ChatDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
<br>
<br>
<br>
- 일단 !!! View만 후딱 만들어봤어요 !!!!!
- 차단하기 Flow
차단하기 버튼 클릭 -> AlertView -> 확인버튼 클릭 시, 차단 (차단되었다는 토스트 뷰) -> 메시지 못보냄
- 차단해제 Flow
차단 해제 버튼 클릭 -> 차단 해제되었다는 토스트 뷰 -> 차단 해제 
- 마루야 ~~ 토스트뷰가 이상해욤 !!!!!!!
<br><br>
> refactor: 채팅방에 사용자 차단하기 버튼 추가

- ANBDModel/Sources/Data/DataSource/PostDataSource.swift
- ANBDModel/Sources/Data/DataSource/UserDataSource.swift
- ANBDModel/Sources/Data/Repository/ArticleRepository.swift
- ANBDModel/Sources/Data/Repository/CommentRepository.swift
- ANBDModel/Sources/Data/Repository/TradeRepository.swift
- ANBDModel/Sources/Data/Repository/UserRepository.swift
- ANBDModel/Sources/Domain/RepositoryProtocol/UserRepositroyProtocol.swift
- ANBDModel/Sources/Domain/Usecase/UserUsecase.swift
- ANBDModel/Sources/Domain/VO/User.swift
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: 사용자 차단 기능 추가

- ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/ChatDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Chat/ViewModel/ChatViewModel.swift
<br>
<br>
<br>
- 토스트뷰 !!!!!!! ㅠ..ㅠ
<br><br>
> feat: 채팅방 사용자 차단 기능 구현

- ANBDConsumer/ANBDConsumer.xcodeproj/project.pbxproj
- ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
- ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/BlockingUserListView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/SettingsView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
- ANBDModel/Sources/Data/DataSource/UserDataSource.swift
> feat: 사용자 정보 페이지에서 사용자 차단하기 기능 추가

- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
> feat: 사용자 차단기능 - 거래글

- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeCreateView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/ViewModel/TradeViewModel.swift
> feat: 이미지 캐싱

- ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/SettingsView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserActivityListView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
> refactor: 마이페이지 기타 기능 수정

- ANBDConsumer/ANBDConsumer/Presentaion/Article/View/ArticleDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Article/ViewModel/ArticleViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/BlockingUserListView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
> refactor: 사용자 차단하기 Toast 문구 수정

- ANBDConsumer/ANBDConsumer/Presentaion/Article/View/ArticleDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Article/ViewModel/ArticleViewModel.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/ChatDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/MessageCell.swift
- ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/ImageDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
- ANBDConsumer/ANBDConsumer/Presentaion/Trade/ViewModel/TradeViewModel.swift
<br>
<br>
<br>
- 브랜치명 잘못 땃더요 .... ㅠㅠ
<br><br>
> refactor: ImageDetailView 이미지 캐싱 및 URL 타입 변환

- ANBDModel/Sources/Data/DataSource/PostDataSource.swift
<br>
<br>
```swift
func readItemList(
category: ANBDCategory,
location: [Location]?,
itemCategory: [ItemCategory]?,
blockList: [String],
limit: Int
) async throws -> [Trade]
var requestQuery = database
.whereField("writerID", notIn: blockList.isEmpty ? [""] : blockList)                 // [!]
.whereField("category", isEqualTo: category.rawValue)
if let filterQuery {
requestQuery = filterQuery
} else {
if let location, let itemCategory {
requestQuery = requestQuery
.whereFilter(
.andFilter([
.whereField("location", in: location.map { $0.rawValue }),           // [!]
.whereField("itemCategory", in: itemCategory.map { $0.rawValue })    // [!]
])
)
} else if let location {
requestQuery = requestQuery
.whereField("location", in: location.map { …
```
> fix: trade 필터링 시  not-in, in을 같이 사용해서 충돌나는 것 해결

- ANBDUIKit/ANBDUIKit.xcodeproj/project.pbxproj
- ANBDUIKit/ANBDUIKit/Common/Extension/UIImage+Extension.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/HomeTradeCell.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/HomeViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/NanuaCollectionViewCell.swift
- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeDetailViewController.swift
<br>
<br>
<br>
- 특이 사항 1
- 특이 사항 2
<br><br>
> feat: home view baccua cell UI

- ANBDUIKit/ANBDUIKit.xcodeproj/project.pbxproj
- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeCreateViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeViewController.swift
> feature: Trade 글쓰기 ViewController 구현

- ANBDUIKit/ANBDUIKit.xcodeproj/project.pbxproj
- ANBDUIKit/ANBDUIKit/App/SceneDelegate.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/ArticleMoreViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/HomeViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Home/TradeMoreViewController.swift
> feature: home view controllers connect

- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeCell.swift
- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeDetailViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeViewController.swift
> refactor: TradeViewController 수정 

- ANBDUIKit/ANBDUIKit.xcodeproj/project.pbxproj
- ANBDUIKit/ANBDUIKit/Presentation/Chat/Chat.swift
- ANBDUIKit/ANBDUIKit/Presentation/Chat/ChatListCell.swift
- ANBDUIKit/ANBDUIKit/Presentation/Chat/ChatViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/CommonUI/ANBDTabBarController.swift
> feature: chat list view

- ANBDUIKit/ANBDUIKit.xcodeproj/project.pbxproj
- ANBDUIKit/ANBDUIKit/Presentation/Authentication/AuthenticationViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Authentication/PasswordViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Authentication/SettingProfileViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Authentication/SignupViewController.swift
- ANBDUIKit/ANBDUIKit/Presentation/Authentication/TermsViewController.swift
> feature: 로그인, 회원가입 뷰 구현

- ANBDUIKit/ANBDUIKit/Presentation/Trade/TradeCreateViewController.swift
> feature: TradeCreateViewController 구현
